### ISSUE TITLE
Nav styling and interaction

### ISSUE THREAD

**Issue by sinc0115** [sinc0115/Rubys-Cupcakes#18]
- Please make the navbar sticky/fixed
- Add some font styles
- Add links to other pages (if the html file has been created)

**Comment by Kakuli-coder** [comment]
![image](https://user-images.githubusercontent.com/79051368/137576309-b209cca7-06ac-4145-96b9-e44af7b2f2ab.png)
![image](https://user-images.githubusercontent.com/79051368/137576311-7cac26f3-375a-4448-9127-f5342de8bdcd.png)
I have styled the navbar as you wanted @sinc0115 but there is some issue in the _Navbar-styling_ branch of my local github repository. Can you help me resolve this so that I create a pull request.
(I have attached screenshots of both the styled navbar and my issue)
